name: MYTELEBOT-CICD
on:
  push:
    branches:
    - develop

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - name: Check
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run test
      run: make test
