name: MyCICD
on:
  push:
    branches:
    - develop

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_TOKEN }}

    - name: Run test
      run: make test

    - name: Build&Push
      env:
        APP: "mytelebot"
      run: make image push